### ISSUE TITLE
Needs some docs on server maintainance

### ISSUE THREAD

**Issue by lazka** [msys2/msys2-main-server#2]
* What needs to be updated and how often.
* How should updates be handled.

**Comment by elieux** [comment]
For security, there's *unattended-upgrades*.

For other updates, I have a weekly to-do. I just run `apt update && apt upgrade`. If it needs to restart containers, I'll probably ask about it first.

Restarts to update kernel and/or firmware don't have a process yet.

**Comment by lazka** [comment]
There is https://github.com/msys2/msys2-main-server/blob/main/MAINTENANCE.md now, which isn't perfect, but feel free to improve it if wanted.
