### ISSUE TITLE
Add mirrorbits in prod

### ISSUE THREAD

**Issue by lazka** [msys2/msys2-main-server#3]
We have a domain now to test things: http://mirror.msys2.org/

Here is where I stopped: https://github.com/msys2/msys2-main-server/tree/mirrorbits (needs work..)

Known problems:

* David said that IP detection didn't work his (home?) IP. And thus location/mirror selection was wrong.

**Comment by elieux** [comment]
I tried now using https://mirror.msys2.org/mingw/i686/mingw32.db?mirrorlist and it seems to detect my work location fine.  Not sure when or where the malfunction happened.

**Comment by lazka** [comment]
Thanks for testing.

My planned next steps:

* Remove slow mirrors again (hungary and ukrain are quite slow)
* Switch the main installer download URL to mirrorbits and see how this works out
* ...

**Comment by lazka** [comment]
pacman fails to sync DB signatures:

```
$ curl -I https://mirror.msys2.org/mingw/clang32/clang32.db.sig
HTTP/2 302
cache-control: private, no-cache
content-type: text/html; charset=utf-8
date: Wed, 16 Jun 2021 19:06:06 GMT
link: <https://repo.msys2.org/mingw/clang32/clang32.db.tar.gz.sig>; rel=duplicate; pri=1; geo=de
location: https://mirror.yandex.ru/mirrors/msys2/mingw/clang32/clang32.db.tar.gz.sig
server: Mirrorbits/v0.5.1-31-geeea0e0-dirty
```

This makes pacman write out a "clang32.db.tar.gz.sig" file and then it errors out because it can't find "clang32.db.sig"

**Comment by lazka** [comment]
This did work with pacman 5 from what I can see.

Two things to do:

* file a bug with pacman
* don't deref symlinks: https://github.com/etix/mirrorbits/blob/eeea0e026d0ca99c7009a91a54369f7c29e87049/filesystem/fs.go#L33

**Comment by lazka** [comment]
I've moved the redirect issue to https://github.com/msys2/msys2-pacman/issues/4

Let's not make this a catch all and close it. It more or less works in prod now, even if it isn't used much.
