### ISSUE TITLE
mirror.msys2.org not working

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/msys2-main-server#41]
attempting to access https://mirror.msys2.org is giving me a message:
```
dial tcp 172.19.0.4:6379: i/o timeout
```

package-grokker is getting 500 errors: https://github.com/msys2/MSYS2-packages/actions/runs/9073218632/job/24930272406

**Comment by lazka** [comment]
Thanks, I downgraded redis to temporarily avoid the issue.

Somehow mirrorbits thinks that redis is too old after the last update

**Comment by lazka** [comment]
After having restarted everything it seems to be fine with the newer version again as well. weird.

For future reference this was the mirrorbits error in the logs "Unsupported Redis version, please upgrade to Redis >= 3.2.0"

**Comment by lazka** [comment]
Looking at the logs this started to happen 3 hours ago, so not directly related to any maintenance.
