### ISSUE TITLE
Limit log sizes

### ISSUE THREAD

**Issue by lazka** [msys2/msys2-main-server#6]
We currently have 6GB of traefik access logs saved by docker. We should somehow limit that, or redirect to journald maybe?

See `ncdu /var/lib/docker/containers/`

**Comment by lazka** [comment]
This seems the easiest: https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver

**Comment by lazka** [comment]
Read some more: https://docs.docker.com/config/containers/logging/configure/

> Docker keeps the json-file logging driver (without log-rotation) as a default to remain backward compatibility

> For other situations, the “local” logging driver is recommended as it performs log-rotation by default

So I think we should try the "local" one. It does 100MB per container by default

**Comment by lazka** [comment]
This is fixed (for some time now), 295MB of logs by using the "local" driver.

Sadly this breaks `docker-compose logs` due to this bug https://github.com/docker/compose/issues/7420

@elieux What about adding a newer docker-compose to ~/bin and that to PATH? -> https://github.com/docker/compose/releases/tag/1.29.2 ?

**Comment by elieux** [comment]
Limiting size is only available to the local driver?

**Comment by elieux** [comment]
I'd rather use a PPA if we're upgrading to newer Compose, but I can't find any.  I'm probably fine with a temporary isolated newer Compose.  It should go away when we upgrade to 22.04.

**Comment by lazka** [comment]
> Limiting size is only available to the local driver?

huh, the docs say it also works with `json-file`.. I wonder if this is new or I just missed it.

**Comment by lazka** [comment]
ah, right, I should read what I wrote back then, I switched to "local" because it is recommended, and since I was already touching the config..

So I guess we'll switch back to json-file for now, with log rotate enabled.

**Comment by lazka** [comment]
ok, switched back (I haven't restarted docker yet): 1757096e1c5a4

I'd say this can be closed then.

Sorry for the noise.
